services:
  app:
    build:
      context: ./BlogBE
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    #this capture the value in .env and pass to container as runtime environment variable values
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTIONSTRINGS__POSTGRESCONNECTION: ${CONNECTIONSTRINGS__POSTGRESCONNECTION}
      CONNECTIONSTRINGS__MONGO: ${CONNECTIONSTRINGS__MONGO}
      CONNECTIONSTRINGS__REDIS: ${CONNECTIONSTRINGS__REDIS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT__SIGNINGKEY: ${JWT__SIGNINGKEY}
    depends_on:
      - postgres
      - mongo
      - redis
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.4
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  postgres_data:
  mongo_data:
  redis_data: